// Generated by CoffeeScript 1.7.1
var gulp, runSequence;

gulp = require('gulp');
runSequence = require('run-sequence');

(function() {
  var bump, index, publish, type, types, _i, _len;
  types = ['prerelease', 'patch', 'minor', 'major'];
  bump = function(type) {
    return function() {
      return gulp.src('./package.json').pipe(require('gulp-bump')({
        type: type
      })).pipe(gulp.dest('./'));
    };
  };
  publish = function(type) {
    return function(cb) {
      var publish;

      publish = function() {
        require('child_process')
          .spawn('npm', ['publish'], {
            stdio: 'inherit'
          })
          .on('close', cb);
      };

      if (type) 
        runSequence(("bump:" + type), publish);
      else
        publish();
    };
  };
  for (index = _i = 0, _len = types.length; _i < _len; index = ++_i) {
    type = types[index];
    gulp.task("bump:" + type, bump(type));
    gulp.task("publish:" + type, publish(type));
  }
  gulp.task('bump', bump('patch'));
  gulp.task('publish', publish());
})();
